export const KEYS = {
  dashboard: {
    title: 'dashboard.title',
    subtitle: 'dashboard.subtitle',
    kpi: {
      totalProducts:    'dashboard.kpi.totalProducts',
      totalProductsSub: 'dashboard.kpi.totalProductsSub',
      inventoryValue:   'dashboard.kpi.inventoryValue',
      inventoryValueSub:'dashboard.kpi.inventoryValueSub',
      totalSales:       'dashboard.kpi.totalSales',
      totalSalesSub:    'dashboard.kpi.totalSalesSub',
      lowStock:         'dashboard.kpi.lowStock',
      lowStockSub:      'dashboard.kpi.lowStockSub',
      outOfStock:       'dashboard.kpi.outOfStock',
      outOfStockSub:    'dashboard.kpi.outOfStockSub',
      topSellingItem:   'dashboard.kpi.topSellingItem',
      topSellingItemSub:'dashboard.kpi.topSellingItemSub',
    },
    chart: {
      salesTrend: 'dashboard.chart.salesTrend',
    },
    topItems: {
      title: 'dashboard.topItems.title',
      empty: 'dashboard.topItems.empty',
    },
    stockHealth: {
      title:      'dashboard.stockHealth.title',
      healthy:    'dashboard.stockHealth.healthy',
      lowStock:   'dashboard.stockHealth.lowStock',
      outOfStock: 'dashboard.stockHealth.outOfStock',
    },
    categories: {
      title: 'dashboard.categories.title',
      empty: 'dashboard.categories.empty',
    },
  },
  nav: {
    dashboard: 'nav.dashboard',
    inventory: 'nav.inventory',
    sales:     'nav.sales',
    orders:    'nav.orders',
    reports:   'nav.reports',
    staff:     'nav.staff',
    settings:  'nav.settings',
    logout:             'nav.logout',
    logoutConfirmTitle: 'nav.logoutConfirmTitle',
    logoutConfirmText:  'nav.logoutConfirmText',
  },
  common: {
    loading:          'common.loading',
    loadingDashboard: 'common.loadingDashboard',
    noData:           'common.noData',
    error:            'common.error',
  },
  auth: {
    brand: {
      headline:      'auth.brand.headline',
      headlineAccent:'auth.brand.headlineAccent',
      sub:           'auth.brand.sub',
      bullet1:       'auth.brand.bullet1',
      bullet2:       'auth.brand.bullet2',
      bullet3:       'auth.brand.bullet3',
      quote:         'auth.brand.quote',
      quoteAttr:     'auth.brand.quoteAttr',
    },
    login: {
      eyebrow:             'auth.login.eyebrow',
      title:               'auth.login.title',
      subtitle:            'auth.login.subtitle',
      emailLabel:          'auth.login.emailLabel',
      emailPlaceholder:    'auth.login.emailPlaceholder',
      passwordLabel:       'auth.login.passwordLabel',
      passwordPlaceholder: 'auth.login.passwordPlaceholder',
      forgotLink:          'auth.login.forgotLink',
      submit:              'auth.login.submit',
      recaptchaError:      'auth.login.recaptchaError',
      errorTitle:          'auth.login.errorTitle',
      errorFallback:       'auth.login.errorFallback',
    },
    forgot: {
      eyebrow:       'auth.forgot.eyebrow',
      title:         'auth.forgot.title',
      subtitle:      'auth.forgot.subtitle',
      label:         'auth.forgot.label',
      placeholder:   'auth.forgot.placeholder',
      submit:        'auth.forgot.submit',
      footerText:    'auth.forgot.footerText',
      footerLink:    'auth.forgot.footerLink',
      sentTitle:     'auth.forgot.sentTitle',
      sentText:      'auth.forgot.sentText',
      errorTitle:    'auth.forgot.errorTitle',
      errorFallback: 'auth.forgot.errorFallback',
    },
    verify: {
      eyebrow:       'auth.verify.eyebrow',
      title:         'auth.verify.title',
      subtitle:      'auth.verify.subtitle',
      submit:        'auth.verify.submit',
      footerText:    'auth.verify.footerText',
      footerLink:    'auth.verify.footerLink',
      errorFallback: 'auth.verify.errorFallback',
    },
    setPassword: {
      eyebrow:            'auth.setPassword.eyebrow',
      title:              'auth.setPassword.title',
      subtitle:           'auth.setPassword.subtitle',
      newLabel:           'auth.setPassword.newLabel',
      newPlaceholder:     'auth.setPassword.newPlaceholder',
      confirmLabel:       'auth.setPassword.confirmLabel',
      confirmPlaceholder: 'auth.setPassword.confirmPlaceholder',
      submit:             'auth.setPassword.submit',
      successTitle:       'auth.setPassword.successTitle',
      successText:        'auth.setPassword.successText',
      errorTitle:         'auth.setPassword.errorTitle',
      errorFallback:      'auth.setPassword.errorFallback',
    },
    validation: {
      emailInvalid:       'auth.validation.emailInvalid',
      emailRequired:      'auth.validation.emailRequired',
      passwordRequired:   'auth.validation.passwordRequired',
      identifierRequired: 'auth.validation.identifierRequired',
      passwordMin:        'auth.validation.passwordMin',
      passwordMismatch:   'auth.validation.passwordMismatch',
      confirmRequired:    'auth.validation.confirmRequired',
    },
  },
} as const;
