export const KEYS = {
  dashboard: {
    title: 'dashboard.title',
    subtitle: 'dashboard.subtitle',
    kpi: {
      totalProducts:    'dashboard.kpi.totalProducts',
      totalProductsSub: 'dashboard.kpi.totalProductsSub',
      inventoryValue:   'dashboard.kpi.inventoryValue',
      inventoryValueSub:'dashboard.kpi.inventoryValueSub',
      totalSales:       'dashboard.kpi.totalSales',
      totalSalesSub:    'dashboard.kpi.totalSalesSub',
      lowStock:         'dashboard.kpi.lowStock',
      lowStockSub:      'dashboard.kpi.lowStockSub',
      outOfStock:       'dashboard.kpi.outOfStock',
      outOfStockSub:    'dashboard.kpi.outOfStockSub',
      topSellingItem:   'dashboard.kpi.topSellingItem',
      topSellingItemSub:'dashboard.kpi.topSellingItemSub',
    },
    chart: {
      salesTrend: 'dashboard.chart.salesTrend',
    },
    topItems: {
      title: 'dashboard.topItems.title',
      empty: 'dashboard.topItems.empty',
    },
    stockHealth: {
      title:      'dashboard.stockHealth.title',
      healthy:    'dashboard.stockHealth.healthy',
      lowStock:   'dashboard.stockHealth.lowStock',
      outOfStock: 'dashboard.stockHealth.outOfStock',
    },
    categories: {
      title: 'dashboard.categories.title',
      empty: 'dashboard.categories.empty',
    },
  },
  nav: {
    dashboard:    'nav.dashboard',
    inventory:    'nav.inventory',
    categories:   'nav.categories',
    sales:        'nav.sales',
    salesHistory:  'nav.salesHistory',
    transactions:  'nav.transactions',
    orders:        'nav.orders',
    reports:      'nav.reports',
    staff:        'nav.staff',
    settings:     'nav.settings',
    logout:             'nav.logout',
    logoutConfirmTitle: 'nav.logoutConfirmTitle',
    logoutConfirmText:  'nav.logoutConfirmText',
  },
  salesHistory: {
    title:    'salesHistory.title',
    subtitle: 'salesHistory.subtitle',
    newSale:  'salesHistory.newSale',
    empty:    'salesHistory.empty',
    table: {
      saleNumber: 'salesHistory.table.saleNumber',
      date:       'salesHistory.table.date',
      cashier:    'salesHistory.table.cashier',
      method:     'salesHistory.table.method',
      amount:     'salesHistory.table.amount',
      status:     'salesHistory.table.status',
      actions:    'salesHistory.table.actions',
    },
    filter: {
      from:       'salesHistory.filter.from',
      to:         'salesHistory.filter.to',
      method:     'salesHistory.filter.method',
      allMethods: 'salesHistory.filter.allMethods',
    },
    status: {
      paid:    'salesHistory.status.paid',
      voided:  'salesHistory.status.voided',
      pending: 'salesHistory.status.pending',
      failed:  'salesHistory.status.failed',
    },
    detail: {
      title:       'salesHistory.detail.title',
      cashier:     'salesHistory.detail.cashier',
      date:        'salesHistory.detail.date',
      method:      'salesHistory.detail.method',
      amount:      'salesHistory.detail.amount',
      discount:    'salesHistory.detail.discount',
      change:      'salesHistory.detail.change',
      statusLabel: 'salesHistory.detail.statusLabel',
      itemsTitle:  'salesHistory.detail.itemsTitle',
      itemProduct: 'salesHistory.detail.itemProduct',
      itemQty:     'salesHistory.detail.itemQty',
      itemPrice:   'salesHistory.detail.itemPrice',
      itemTotal:   'salesHistory.detail.itemTotal',
      noItems:     'salesHistory.detail.noItems',
      voidBtn:     'salesHistory.detail.voidBtn',
      close:       'salesHistory.detail.close',
    },
    void: {
      confirmTitle: 'salesHistory.void.confirmTitle',
      confirmText:  'salesHistory.void.confirmText',
      success:      'salesHistory.void.success',
      error:        'salesHistory.void.error',
    },
  },
  transactions: {
    title:    'transactions.title',
    subtitle: 'transactions.subtitle',
    empty:    'transactions.empty',
    stats: {
      totalCount:   'transactions.stats.totalCount',
      cashTotal:    'transactions.stats.cashTotal',
      momoTotal:    'transactions.stats.momoTotal',
      pendingTotal: 'transactions.stats.pendingTotal',
    },
    filter: {
      from:       'transactions.filter.from',
      to:         'transactions.filter.to',
      method:     'transactions.filter.method',
      status:     'transactions.filter.status',
      allMethods: 'transactions.filter.allMethods',
      allStatus:  'transactions.filter.allStatus',
    },
    table: {
      date:       'transactions.table.date',
      saleNumber: 'transactions.table.saleNumber',
      cashier:    'transactions.table.cashier',
      method:     'transactions.table.method',
      amount:     'transactions.table.amount',
      status:     'transactions.table.status',
      reference:  'transactions.table.reference',
      phone:      'transactions.table.phone',
      actions:    'transactions.table.actions',
    },
    status: {
      paid:    'transactions.status.paid',
      pending: 'transactions.status.pending',
      failed:  'transactions.status.failed',
    },
    verify: {
      btn:              'transactions.verify.btn',
      confirmTitle:     'transactions.verify.confirmTitle',
      confirmText:      'transactions.verify.confirmText',
      successTitle:     'transactions.verify.successTitle',
      successText:      'transactions.verify.successText',
      stillPendingTitle:'transactions.verify.stillPendingTitle',
      alreadyPaid:      'transactions.verify.alreadyPaid',
      error:            'transactions.verify.error',
    },
  },
  common: {
    loading:             'common.loading',
    loadingDashboard:    'common.loadingDashboard',
    noData:              'common.noData',
    error:               'common.error',
    edit:                'common.edit',
    partialDataWarning:  'common.partialDataWarning',
    apply:               'common.apply',
    clear:               'common.clear',
    viewBtn:             'common.viewBtn',
    pickDate:            'common.pickDate',
    cancel:              'common.cancel',
    method: {
      cash: 'common.method.cash',
      momo: 'common.method.momo',
    },
  },
  staff: {
    title:    'staff.title',
    subtitle: 'staff.subtitle',
    addStaff: 'staff.addStaff',
    search:   'staff.search',
    edit:     'staff.edit',
    deactivate:   'staff.deactivate',
    reactivate:   'staff.reactivate',
    confirmDeactivateTitle: 'staff.confirmDeactivateTitle',
    confirmDeactivateText:  'staff.confirmDeactivateText',
    confirmReactivateTitle: 'staff.confirmReactivateTitle',
    confirmReactivateText:  'staff.confirmReactivateText',
    inviteSentTitle:     'staff.inviteSentTitle',
    inviteSentText:      'staff.inviteSentText',
    successUpdateTitle:  'staff.successUpdateTitle',
    successUpdateText:   'staff.successUpdateText',
    errorCreateTitle:    'staff.errorCreateTitle',
    errorCreateFallback: 'staff.errorCreateFallback',
    errorUpdateTitle:    'staff.errorUpdateTitle',
    errorUpdateFallback: 'staff.errorUpdateFallback',
    errorToggleTitle:    'staff.errorToggleTitle',
    errorToggleFallback: 'staff.errorToggleFallback',
    table: {
      name:    'staff.table.name',
      phone:   'staff.table.phone',
      role:    'staff.table.role',
      status:  'staff.table.status',
      noRole:  'staff.table.noRole',
      empty:   'staff.table.empty',
    },
    status: {
      active:   'staff.status.active',
      inactive: 'staff.status.inactive',
      pending:  'staff.status.pending',
    },
    stat: {
      total:    'staff.stat.total',
      active:   'staff.stat.active',
      inactive: 'staff.stat.inactive',
      pending:  'staff.stat.pending',
    },
    filter: {
      all:      'staff.filter.all',
      active:   'staff.filter.active',
      inactive: 'staff.filter.inactive',
      pending:  'staff.filter.pending',
    },
    pendingBadge: 'staff.pendingBadge',
    loadError:    'staff.loadError',
    resendInvite: 'staff.resendInvite',
    cancelInvite: 'staff.cancelInvite',
    confirmResendInviteTitle: 'staff.confirmResendInviteTitle',
    confirmResendInviteText:  'staff.confirmResendInviteText',
    confirmCancelInviteTitle: 'staff.confirmCancelInviteTitle',
    confirmCancelInviteText:  'staff.confirmCancelInviteText',
    inviteResentTitle:     'staff.inviteResentTitle',
    inviteResentText:      'staff.inviteResentText',
    inviteCancelledTitle:  'staff.inviteCancelledTitle',
    inviteCancelledText:   'staff.inviteCancelledText',
    errorResendTitle:      'staff.errorResendTitle',
    errorResendFallback:   'staff.errorResendFallback',
    errorCancelTitle:      'staff.errorCancelTitle',
    errorCancelFallback:   'staff.errorCancelFallback',
    form: {
      createTitle:        'staff.form.createTitle',
      editTitle:          'staff.form.editTitle',
      name:               'staff.form.name',
      namePlaceholder:    'staff.form.namePlaceholder',
      email:              'staff.form.email',
      emailPlaceholder:   'staff.form.emailPlaceholder',
      phone:              'staff.form.phone',
      phonePlaceholder:   'staff.form.phonePlaceholder',
      role:               'staff.form.role',
      rolePlaceholder:    'staff.form.rolePlaceholder',
      submitCreate:       'staff.form.submitCreate',
      submitUpdate:       'staff.form.submitUpdate',
      inviteHint:         'staff.form.inviteHint',
      validation: {
        nameRequired:   'staff.form.validation.nameRequired',
        emailRequired:  'staff.form.validation.emailRequired',
        emailInvalid:   'staff.form.validation.emailInvalid',
        emailDuplicate: 'staff.form.validation.emailDuplicate',
        phoneRequired:  'staff.form.validation.phoneRequired',
        phoneDuplicate: 'staff.form.validation.phoneDuplicate',
        roleRequired:   'staff.form.validation.roleRequired',
      },
    },
  },
  roles: {
    createNew:          'roles.createNew',
    form: {
      title:            'roles.form.title',
      name:             'roles.form.name',
      namePlaceholder:  'roles.form.namePlaceholder',
      permissions:      'roles.form.permissions',
      submit:           'roles.form.submit',
      sensitive:        'roles.form.sensitive',
      nameRequired:     'roles.form.nameRequired',
    },
    errorCreateTitle:    'roles.errorCreateTitle',
    errorCreateFallback: 'roles.errorCreateFallback',
  },
  forceChangePassword: {
    title:              'forceChangePassword.title',
    subtitle:           'forceChangePassword.subtitle',
    currentLabel:       'forceChangePassword.currentLabel',
    currentPlaceholder: 'forceChangePassword.currentPlaceholder',
    newLabel:           'forceChangePassword.newLabel',
    newPlaceholder:     'forceChangePassword.newPlaceholder',
    confirmLabel:       'forceChangePassword.confirmLabel',
    confirmPlaceholder: 'forceChangePassword.confirmPlaceholder',
    submit:             'forceChangePassword.submit',
    successTitle:       'forceChangePassword.successTitle',
    successText:        'forceChangePassword.successText',
    errorTitle:         'forceChangePassword.errorTitle',
    errorFallback:      'forceChangePassword.errorFallback',
    validation: {
      currentRequired:  'forceChangePassword.validation.currentRequired',
      newMin:           'forceChangePassword.validation.newMin',
      confirmMismatch:  'forceChangePassword.validation.confirmMismatch',
    },
  },
  auth: {
    brand: {
      headline:      'auth.brand.headline',
      headlineAccent:'auth.brand.headlineAccent',
      sub:           'auth.brand.sub',
      bullet1:       'auth.brand.bullet1',
      bullet2:       'auth.brand.bullet2',
      bullet3:       'auth.brand.bullet3',
      quote:         'auth.brand.quote',
      quoteAttr:     'auth.brand.quoteAttr',
    },
    login: {
      eyebrow:             'auth.login.eyebrow',
      title:               'auth.login.title',
      subtitle:            'auth.login.subtitle',
      emailLabel:          'auth.login.emailLabel',
      emailPlaceholder:    'auth.login.emailPlaceholder',
      passwordLabel:       'auth.login.passwordLabel',
      passwordPlaceholder: 'auth.login.passwordPlaceholder',
      forgotLink:          'auth.login.forgotLink',
      submit:              'auth.login.submit',
      recaptchaError:      'auth.login.recaptchaError',
      errorTitle:          'auth.login.errorTitle',
      errorFallback:       'auth.login.errorFallback',
    },
    forgot: {
      eyebrow:       'auth.forgot.eyebrow',
      title:         'auth.forgot.title',
      subtitle:      'auth.forgot.subtitle',
      label:         'auth.forgot.label',
      placeholder:   'auth.forgot.placeholder',
      submit:        'auth.forgot.submit',
      footerText:    'auth.forgot.footerText',
      footerLink:    'auth.forgot.footerLink',
      sentTitle:     'auth.forgot.sentTitle',
      sentText:      'auth.forgot.sentText',
      errorTitle:    'auth.forgot.errorTitle',
      errorFallback: 'auth.forgot.errorFallback',
    },
    verify: {
      eyebrow:       'auth.verify.eyebrow',
      title:         'auth.verify.title',
      subtitle:      'auth.verify.subtitle',
      submit:        'auth.verify.submit',
      footerText:    'auth.verify.footerText',
      footerLink:    'auth.verify.footerLink',
      errorFallback: 'auth.verify.errorFallback',
    },
    setPassword: {
      eyebrow:            'auth.setPassword.eyebrow',
      title:              'auth.setPassword.title',
      subtitle:           'auth.setPassword.subtitle',
      newLabel:           'auth.setPassword.newLabel',
      newPlaceholder:     'auth.setPassword.newPlaceholder',
      confirmLabel:       'auth.setPassword.confirmLabel',
      confirmPlaceholder: 'auth.setPassword.confirmPlaceholder',
      submit:             'auth.setPassword.submit',
      successTitle:       'auth.setPassword.successTitle',
      successText:        'auth.setPassword.successText',
      errorTitle:         'auth.setPassword.errorTitle',
      errorFallback:      'auth.setPassword.errorFallback',
    },
    validation: {
      emailInvalid:       'auth.validation.emailInvalid',
      emailRequired:      'auth.validation.emailRequired',
      passwordRequired:   'auth.validation.passwordRequired',
      identifierRequired: 'auth.validation.identifierRequired',
      passwordMin:        'auth.validation.passwordMin',
      passwordMismatch:   'auth.validation.passwordMismatch',
      confirmRequired:    'auth.validation.confirmRequired',
    },
  },
  products: {
    title:              'products.title',
    subtitle:           'products.subtitle',
    addBtn:             'products.addBtn',
    searchPlaceholder:  'products.searchPlaceholder',
    categoryFilter:     'products.categoryFilter',
    empty:              'products.empty',
    viewVariants:       'products.viewVariants',
    table: {
      name:     'products.table.name',
      category: 'products.table.category',
      brand:    'products.table.brand',
      variants: 'products.table.variants',
      status:   'products.table.status',
      actions:  'products.table.actions',
    },
    status: {
      active:   'products.status.active',
      inactive: 'products.status.inactive',
    },
    drawer: {
      addTitle:         'products.drawer.addTitle',
      editTitle:        'products.drawer.editTitle',
      nameLabel:        'products.drawer.nameLabel',
      namePlaceholder:  'products.drawer.namePlaceholder',
      categoryLabel:    'products.drawer.categoryLabel',
      categoryPlaceholder: 'products.drawer.categoryPlaceholder',
      brandLabel:       'products.drawer.brandLabel',
      brandPlaceholder: 'products.drawer.brandPlaceholder',
      descLabel:        'products.drawer.descLabel',
      descPlaceholder:  'products.drawer.descPlaceholder',
      submitAdd:        'products.drawer.submitAdd',
      submitEdit:       'products.drawer.submitEdit',
      cancel:           'products.drawer.cancel',
    },
    confirm: {
      deactivateTitle: 'products.confirm.deactivateTitle',
      deactivateText:  'products.confirm.deactivateText',
      activateTitle:   'products.confirm.activateTitle',
      activateText:    'products.confirm.activateText',
      confirmBtn:      'products.confirm.confirmBtn',
    },
    validation: {
      nameRequired:     'products.validation.nameRequired',
      categoryRequired: 'products.validation.categoryRequired',
    },
    toast: {
      created:        'products.toast.created',
      updated:        'products.toast.updated',
      deactivated:    'products.toast.deactivated',
      activated:      'products.toast.activated',
      createError:    'products.toast.createError',
      updateError:    'products.toast.updateError',
      statusError:    'products.toast.statusError',
    },
    images: {
      sectionLabel: 'products.images.sectionLabel',
      dropHint:     'products.images.dropHint',
      browseHint:   'products.images.browseHint',
      typeHint:     'products.images.typeHint',
      maxReached:   'products.images.maxReached',
      removeLabel:  'products.images.removeLabel',
      removeError:  'products.images.removeError',
      required:     'products.images.required',
    },
    gallery: {
      title:      'products.gallery.title',
      editImages: 'products.gallery.editImages',
      save:       'products.gallery.save',
    },
  },
  variants: {
    title:          'variants.title',
    subtitle:       'variants.subtitle',
    backToProducts: 'variants.backToProducts',
    addBtn:         'variants.addBtn',
    empty:          'variants.empty',
    noProduct:      'variants.noProduct',
    table: {
      sku:       'variants.table.sku',
      options:   'variants.table.options',
      costPrice: 'variants.table.costPrice',
      sellPrice: 'variants.table.sellPrice',
      stock:     'variants.table.stock',
      threshold: 'variants.table.threshold',
      status:    'variants.table.status',
      actions:   'variants.table.actions',
    },
    status: {
      active:     'variants.status.active',
      lowStock:   'variants.status.lowStock',
      outOfStock: 'variants.status.outOfStock',
      inactive:   'variants.status.inactive',
    },
    form: {
      addTitle:          'variants.form.addTitle',
      skuLabel:          'variants.form.skuLabel',
      skuPlaceholder:    'variants.form.skuPlaceholder',
      costLabel:         'variants.form.costLabel',
      sellLabel:         'variants.form.sellLabel',
      thresholdLabel:    'variants.form.thresholdLabel',
      optionsLabel:      'variants.form.optionsLabel',
      submit:            'variants.form.submit',
      cancel:            'variants.form.cancel',
      validation: {
        costRequired: 'variants.form.validation.costRequired',
        sellRequired: 'variants.form.validation.sellRequired',
      },
    },
    options: {
      panelTitle:          'variants.options.panelTitle',
      addTypePlaceholder:  'variants.options.addTypePlaceholder',
      addTypeBtn:          'variants.options.addTypeBtn',
      addValuePlaceholder: 'variants.options.addValuePlaceholder',
      addValueBtn:         'variants.options.addValueBtn',
      deleteTypeTitle:     'variants.options.deleteTypeTitle',
      deleteTypeText:      'variants.options.deleteTypeText',
      emptyTypes:          'variants.options.emptyTypes',
    },
    stock: {
      addTitle:      'variants.stock.addTitle',
      adjustTitle:   'variants.stock.adjustTitle',
      historyTitle:  'variants.stock.historyTitle',
      quantityLabel: 'variants.stock.quantityLabel',
      noteLabel:     'variants.stock.noteLabel',
      notePlaceholder: 'variants.stock.notePlaceholder',
      submitAdd:     'variants.stock.submitAdd',
      submitAdjust:  'variants.stock.submitAdjust',
      empty:         'variants.stock.empty',
      thresholdLabel: 'variants.stock.thresholdLabel',
      addBtn:        'variants.stock.addBtn',
      adjustBtn:     'variants.stock.adjustBtn',
      historyBtn:    'variants.stock.historyBtn',
      adjustDesc:         'variants.stock.adjustDesc',
      insufficientError:  'variants.stock.insufficientError',
      validation: {
        quantityRequired: 'variants.stock.validation.quantityRequired',
        quantityPositive: 'variants.stock.validation.quantityPositive',
        quantityNonZero:  'variants.stock.validation.quantityNonZero',
        noteRequired:     'variants.stock.validation.noteRequired',
      },
    },
    tooltip: {
      activate:   'variants.tooltip.activate',
      deactivate: 'variants.tooltip.deactivate',
    },
    toast: {
      created:          'variants.toast.created',
      stockAdded:       'variants.toast.stockAdded',
      stockAdjusted:    'variants.toast.stockAdjusted',
      thresholdUpdated: 'variants.toast.thresholdUpdated',
      activated:        'variants.toast.activated',
      deactivated:      'variants.toast.deactivated',
      error:            'variants.toast.error',
    },
  },
  pos: {
    title:            'pos.title',
    subtitle:         'pos.subtitle',
    searchPlaceholder:'pos.searchPlaceholder',
    searchEmpty:      'pos.searchEmpty',
    searchHint:       'pos.searchHint',
    outOfStock:       'pos.outOfStock',
    outOfStockDetail: 'pos.outOfStockDetail',
    stockRemaining:   'pos.stockRemaining',
    cart: {
      title:      'pos.cart.title',
      empty:      'pos.cart.empty',
      subtotal:   'pos.cart.subtotal',
      discount:   'pos.cart.discount',
      total:      'pos.cart.total',
      checkout:   'pos.cart.checkout',
      hold:       'pos.cart.hold',
      clear:      'pos.cart.clear',
      heldLabel:  'pos.cart.heldLabel',
      clearTitle: 'pos.cart.clearTitle',
      clearBody:  'pos.cart.clearBody',
    },
    item: {
      remove:        'pos.item.remove',
      overridePrice: 'pos.item.overridePrice',
      resetOverride: 'pos.item.resetOverride',
    },
    payment: {
      title:           'pos.payment.title',
      cash:            'pos.payment.cash',
      momo:            'pos.payment.momo',
      split:           'pos.payment.split',
      amountDue:       'pos.payment.amountDue',
      amountTendered:  'pos.payment.amountTendered',
      change:          'pos.payment.change',
      phone:           'pos.payment.phone',
      phonePlaceholder:'pos.payment.phonePlaceholder',
      network:         'pos.payment.network',
      confirm:         'pos.payment.confirm',
      pending:         'pos.payment.pending',
      pendingHint:     'pos.payment.pendingHint',
      paid:            'pos.payment.paid',
      failed:          'pos.payment.failed',
      failedHint:      'pos.payment.failedHint',
      retryBtn:        'pos.payment.retryBtn',
      cancel:          'pos.payment.cancel',
      mtn:             'pos.payment.mtn',
      vod:             'pos.payment.vod',
      atl:             'pos.payment.atl',
      unknownNetwork:  'pos.payment.unknownNetwork',
      splitCashLabel:  'pos.payment.splitCashLabel',
      splitMomoLabel:  'pos.payment.splitMomoLabel',
      splitMomoAmount: 'pos.payment.splitMomoAmount',
    },
    receipt: {
      title:        'pos.receipt.title',
      print:        'pos.receipt.print',
      close:        'pos.receipt.close',
      cashier:      'pos.receipt.cashier',
      total:        'pos.receipt.total',
      discount:     'pos.receipt.discount',
      subtotal:     'pos.receipt.subtotal',
      payment:      'pos.receipt.payment',
      change:       'pos.receipt.change',
      refundPolicy: 'pos.receipt.refundPolicy',
      taxBreakdown: 'pos.receipt.taxBreakdown',
      vat:          'pos.receipt.vat',
      nhil:         'pos.receipt.nhil',
      getfund:      'pos.receipt.getfund',
      covidLevy:    'pos.receipt.covidLevy',
    },
    hold: {
      drawerTitle:        'pos.hold.drawerTitle',
      empty:              'pos.hold.empty',
      recall:             'pos.hold.recall',
      deleteLabel:        'pos.hold.deleteLabel',
      confirmReplace:     'pos.hold.confirmReplace',
      confirmReplaceText: 'pos.hold.confirmReplaceText',
      maxReached:         'pos.hold.maxReached',
      savedLabel:         'pos.hold.savedLabel',
    },
    toast: {
      saleComplete: 'pos.toast.saleComplete',
      saleError:    'pos.toast.saleError',
      held:         'pos.toast.held',
      noPermission: 'pos.toast.noPermission',
    },
    validation: {
      phoneRequired:      'pos.validation.phoneRequired',
      phoneMin:           'pos.validation.phoneMin',
      tenderRequired:     'pos.validation.tenderRequired',
      tenderMin:          'pos.validation.tenderMin',
      splitCashRequired:  'pos.validation.splitCashRequired',
      splitCashMax:       'pos.validation.splitCashMax',
    },
    discountLabel:       'pos.discountLabel',
    discountPlaceholder: 'pos.discountPlaceholder',
    noPermission:        'pos.noPermission',
    idleLock: {
      title:   'pos.idleLock.title',
      message: 'pos.idleLock.message',
      unlock:  'pos.idleLock.unlock',
    },
  },
  settings: {
    title:                'settings.title',
    subtitle:             'settings.subtitle',
    saveBtn:              'settings.saveBtn',
    readOnly:             'settings.readOnly',
    restartRequired:      'settings.restartRequired',
    restartRequiredHint:  'settings.restartRequiredHint',
    saved:                'settings.saved',
    saveError:            'settings.saveError',
    unsavedPrompt:        'settings.unsavedPrompt',
    unsavedBody:          'settings.unsavedBody',
    emptyGroup:           'settings.emptyGroup',
    groups: {
      general:    'settings.groups.general',
      inventory:  'settings.groups.inventory',
      payments:   'settings.groups.payments',
      reports:    'settings.groups.reports',
      ecommerce:  'settings.groups.ecommerce',
    },
  },
  notifications: {
    panelTitle:    'notifications.panelTitle',
    empty:         'notifications.empty',
    markRead:      'notifications.markRead',
    justNow:       'notifications.justNow',
    minutesAgo:    'notifications.minutesAgo',
    hoursAgo:      'notifications.hoursAgo',
    daysAgo:       'notifications.daysAgo',
  },
  categories: {
    title:    'categories.title',
    subtitle: 'categories.subtitle',
    addBtn:   'categories.addBtn',
    empty:    'categories.empty',
    table: {
      name:    'categories.table.name',
      created: 'categories.table.created',
      actions: 'categories.table.actions',
    },
    modal: {
      addTitle:        'categories.modal.addTitle',
      editTitle:       'categories.modal.editTitle',
      nameLabel:       'categories.modal.nameLabel',
      namePlaceholder: 'categories.modal.namePlaceholder',
      submit:          'categories.modal.submit',
      cancel:          'categories.modal.cancel',
    },
    confirm: {
      deleteTitle: 'categories.confirm.deleteTitle',
      deleteText:  'categories.confirm.deleteText',
    },
    validation: {
      nameRequired: 'categories.validation.nameRequired',
    },
    toast: {
      created:     'categories.toast.created',
      updated:     'categories.toast.updated',
      deleted:     'categories.toast.deleted',
      inUse:       'categories.toast.inUse',
      error:       'categories.toast.error',
    },
  },
  bulkImport: {
    btnLabel:         'bulkImport.btnLabel',
    modalTitle:       'bulkImport.modalTitle',
    modalSubtitle:    'bulkImport.modalSubtitle',
    downloadTemplate: 'bulkImport.downloadTemplate',
    dropHint:         'bulkImport.dropHint',
    dropSubhint:      'bulkImport.dropSubhint',
    fileSelected:     'bulkImport.fileSelected',
    uploadBtn:        'bulkImport.uploadBtn',
    uploading:        'bulkImport.uploading',
    successTitle:     'bulkImport.successTitle',
    errorTitle:       'bulkImport.errorTitle',
    errorFallback:    'bulkImport.errorFallback',
    noFile:           'bulkImport.noFile',
    result: {
      productsCreated: 'bulkImport.result.productsCreated',
      variantsCreated: 'bulkImport.result.variantsCreated',
      skipped:         'bulkImport.result.skipped',
      errors:          'bulkImport.result.errors',
      reportSent:      'bulkImport.result.reportSent',
    },
  },
} as const;
