export const KEYS = {
  dashboard: {
    title: 'dashboard.title',
    subtitle: 'dashboard.subtitle',
    kpi: {
      totalProducts:    'dashboard.kpi.totalProducts',
      totalProductsSub: 'dashboard.kpi.totalProductsSub',
      inventoryValue:   'dashboard.kpi.inventoryValue',
      inventoryValueSub:'dashboard.kpi.inventoryValueSub',
      totalSales:       'dashboard.kpi.totalSales',
      totalSalesSub:    'dashboard.kpi.totalSalesSub',
      lowStock:         'dashboard.kpi.lowStock',
      lowStockSub:      'dashboard.kpi.lowStockSub',
      outOfStock:       'dashboard.kpi.outOfStock',
      outOfStockSub:    'dashboard.kpi.outOfStockSub',
      topSellingItem:   'dashboard.kpi.topSellingItem',
      topSellingItemSub:'dashboard.kpi.topSellingItemSub',
    },
    chart: {
      salesTrend: 'dashboard.chart.salesTrend',
    },
    topItems: {
      title: 'dashboard.topItems.title',
      empty: 'dashboard.topItems.empty',
    },
    stockHealth: {
      title:      'dashboard.stockHealth.title',
      healthy:    'dashboard.stockHealth.healthy',
      lowStock:   'dashboard.stockHealth.lowStock',
      outOfStock: 'dashboard.stockHealth.outOfStock',
    },
    categories: {
      title: 'dashboard.categories.title',
      empty: 'dashboard.categories.empty',
    },
  },
  nav: {
    dashboard: 'nav.dashboard',
    inventory: 'nav.inventory',
    sales:     'nav.sales',
    orders:    'nav.orders',
    reports:   'nav.reports',
    staff:     'nav.staff',
    settings:  'nav.settings',
    logout:             'nav.logout',
    logoutConfirmTitle: 'nav.logoutConfirmTitle',
    logoutConfirmText:  'nav.logoutConfirmText',
  },
  common: {
    loading:          'common.loading',
    loadingDashboard: 'common.loadingDashboard',
    noData:           'common.noData',
    error:            'common.error',
    cancel:           'common.cancel',
  },
  staff: {
    title:    'staff.title',
    subtitle: 'staff.subtitle',
    addStaff: 'staff.addStaff',
    search:   'staff.search',
    edit:     'staff.edit',
    deactivate:   'staff.deactivate',
    reactivate:   'staff.reactivate',
    confirmDeactivateTitle: 'staff.confirmDeactivateTitle',
    confirmDeactivateText:  'staff.confirmDeactivateText',
    confirmReactivateTitle: 'staff.confirmReactivateTitle',
    confirmReactivateText:  'staff.confirmReactivateText',
    inviteSentTitle:     'staff.inviteSentTitle',
    inviteSentText:      'staff.inviteSentText',
    successUpdateTitle:  'staff.successUpdateTitle',
    successUpdateText:   'staff.successUpdateText',
    errorCreateTitle:    'staff.errorCreateTitle',
    errorCreateFallback: 'staff.errorCreateFallback',
    errorUpdateTitle:    'staff.errorUpdateTitle',
    errorUpdateFallback: 'staff.errorUpdateFallback',
    errorToggleTitle:    'staff.errorToggleTitle',
    errorToggleFallback: 'staff.errorToggleFallback',
    table: {
      name:    'staff.table.name',
      phone:   'staff.table.phone',
      role:    'staff.table.role',
      status:  'staff.table.status',
      noRole:  'staff.table.noRole',
      empty:   'staff.table.empty',
    },
    status: {
      active:   'staff.status.active',
      inactive: 'staff.status.inactive',
      pending:  'staff.status.pending',
    },
    stat: {
      total:    'staff.stat.total',
      active:   'staff.stat.active',
      inactive: 'staff.stat.inactive',
      pending:  'staff.stat.pending',
    },
    filter: {
      all:      'staff.filter.all',
      active:   'staff.filter.active',
      inactive: 'staff.filter.inactive',
      pending:  'staff.filter.pending',
    },
    pendingBadge: 'staff.pendingBadge',
    loadError:    'staff.loadError',
    resendInvite: 'staff.resendInvite',
    cancelInvite: 'staff.cancelInvite',
    confirmResendInviteTitle: 'staff.confirmResendInviteTitle',
    confirmResendInviteText:  'staff.confirmResendInviteText',
    confirmCancelInviteTitle: 'staff.confirmCancelInviteTitle',
    confirmCancelInviteText:  'staff.confirmCancelInviteText',
    inviteResentTitle:     'staff.inviteResentTitle',
    inviteResentText:      'staff.inviteResentText',
    inviteCancelledTitle:  'staff.inviteCancelledTitle',
    inviteCancelledText:   'staff.inviteCancelledText',
    errorResendTitle:      'staff.errorResendTitle',
    errorResendFallback:   'staff.errorResendFallback',
    errorCancelTitle:      'staff.errorCancelTitle',
    errorCancelFallback:   'staff.errorCancelFallback',
    form: {
      createTitle:        'staff.form.createTitle',
      editTitle:          'staff.form.editTitle',
      name:               'staff.form.name',
      namePlaceholder:    'staff.form.namePlaceholder',
      email:              'staff.form.email',
      emailPlaceholder:   'staff.form.emailPlaceholder',
      phone:              'staff.form.phone',
      phonePlaceholder:   'staff.form.phonePlaceholder',
      role:               'staff.form.role',
      rolePlaceholder:    'staff.form.rolePlaceholder',
      submitCreate:       'staff.form.submitCreate',
      submitUpdate:       'staff.form.submitUpdate',
      inviteHint:         'staff.form.inviteHint',
      validation: {
        nameRequired:   'staff.form.validation.nameRequired',
        emailRequired:  'staff.form.validation.emailRequired',
        emailInvalid:   'staff.form.validation.emailInvalid',
        emailDuplicate: 'staff.form.validation.emailDuplicate',
        phoneRequired:  'staff.form.validation.phoneRequired',
        phoneDuplicate: 'staff.form.validation.phoneDuplicate',
        roleRequired:   'staff.form.validation.roleRequired',
      },
    },
  },
  roles: {
    createNew:          'roles.createNew',
    form: {
      title:            'roles.form.title',
      name:             'roles.form.name',
      namePlaceholder:  'roles.form.namePlaceholder',
      permissions:      'roles.form.permissions',
      submit:           'roles.form.submit',
      sensitive:        'roles.form.sensitive',
      nameRequired:     'roles.form.nameRequired',
    },
    errorCreateTitle:    'roles.errorCreateTitle',
    errorCreateFallback: 'roles.errorCreateFallback',
  },
  auth: {
    brand: {
      headline:      'auth.brand.headline',
      headlineAccent:'auth.brand.headlineAccent',
      sub:           'auth.brand.sub',
      bullet1:       'auth.brand.bullet1',
      bullet2:       'auth.brand.bullet2',
      bullet3:       'auth.brand.bullet3',
      quote:         'auth.brand.quote',
      quoteAttr:     'auth.brand.quoteAttr',
    },
    login: {
      eyebrow:             'auth.login.eyebrow',
      title:               'auth.login.title',
      subtitle:            'auth.login.subtitle',
      emailLabel:          'auth.login.emailLabel',
      emailPlaceholder:    'auth.login.emailPlaceholder',
      passwordLabel:       'auth.login.passwordLabel',
      passwordPlaceholder: 'auth.login.passwordPlaceholder',
      forgotLink:          'auth.login.forgotLink',
      submit:              'auth.login.submit',
      recaptchaError:      'auth.login.recaptchaError',
      errorTitle:          'auth.login.errorTitle',
      errorFallback:       'auth.login.errorFallback',
    },
    forgot: {
      eyebrow:       'auth.forgot.eyebrow',
      title:         'auth.forgot.title',
      subtitle:      'auth.forgot.subtitle',
      label:         'auth.forgot.label',
      placeholder:   'auth.forgot.placeholder',
      submit:        'auth.forgot.submit',
      footerText:    'auth.forgot.footerText',
      footerLink:    'auth.forgot.footerLink',
      sentTitle:     'auth.forgot.sentTitle',
      sentText:      'auth.forgot.sentText',
      errorTitle:    'auth.forgot.errorTitle',
      errorFallback: 'auth.forgot.errorFallback',
    },
    verify: {
      eyebrow:       'auth.verify.eyebrow',
      title:         'auth.verify.title',
      subtitle:      'auth.verify.subtitle',
      submit:        'auth.verify.submit',
      footerText:    'auth.verify.footerText',
      footerLink:    'auth.verify.footerLink',
      errorFallback: 'auth.verify.errorFallback',
    },
    setPassword: {
      eyebrow:            'auth.setPassword.eyebrow',
      title:              'auth.setPassword.title',
      subtitle:           'auth.setPassword.subtitle',
      newLabel:           'auth.setPassword.newLabel',
      newPlaceholder:     'auth.setPassword.newPlaceholder',
      confirmLabel:       'auth.setPassword.confirmLabel',
      confirmPlaceholder: 'auth.setPassword.confirmPlaceholder',
      submit:             'auth.setPassword.submit',
      successTitle:       'auth.setPassword.successTitle',
      successText:        'auth.setPassword.successText',
      errorTitle:         'auth.setPassword.errorTitle',
      errorFallback:      'auth.setPassword.errorFallback',
    },
    validation: {
      emailInvalid:       'auth.validation.emailInvalid',
      emailRequired:      'auth.validation.emailRequired',
      passwordRequired:   'auth.validation.passwordRequired',
      identifierRequired: 'auth.validation.identifierRequired',
      passwordMin:        'auth.validation.passwordMin',
      passwordMismatch:   'auth.validation.passwordMismatch',
      confirmRequired:    'auth.validation.confirmRequired',
    },
  },
} as const;
