export const SETTINGS = {
  BUSINESS_NAME:                 'BUSINESS_NAME',
  BUSINESS_TAGLINE:              'BUSINESS_TAGLINE',
  BUSINESS_PHONE:                'BUSINESS_PHONE',
  BUSINESS_EMAIL:                'BUSINESS_EMAIL',
  BUSINESS_WEBSITE:              'BUSINESS_WEBSITE',
  BUSINESS_REGISTRATION_NUMBER:  'BUSINESS_REGISTRATION_NUMBER',
  GRA_TIN:                       'GRA_TIN',
  RECEIPT_STORE_ADDRESS:         'RECEIPT_STORE_ADDRESS',
  RECEIPT_FOOTER_MESSAGE:        'RECEIPT_FOOTER_MESSAGE',
  RECEIPT_FOOTER_LINE_2:         'RECEIPT_FOOTER_LINE_2',
  RECEIPT_PAPER_WIDTH:           'RECEIPT_PAPER_WIDTH',
  RECEIPT_SHOW_LOGO:             'RECEIPT_SHOW_LOGO',
  RECEIPT_SHOW_CASHIER:          'RECEIPT_SHOW_CASHIER',
  RECEIPT_SHOW_REFUND_POLICY:    'RECEIPT_SHOW_REFUND_POLICY',
  RECEIPT_SHOW_PHONE:            'RECEIPT_SHOW_PHONE',
  RECEIPT_SHOW_EMAIL:            'RECEIPT_SHOW_EMAIL',
  RECEIPT_SHOW_WEBSITE:          'RECEIPT_SHOW_WEBSITE',
  RECEIPT_SHOW_SALE_REF:         'RECEIPT_SHOW_SALE_REF',
  RECEIPT_SHOW_UNIT_PRICES:      'RECEIPT_SHOW_UNIT_PRICES',
  RECEIPT_SHOW_ITEM_SKU:         'RECEIPT_SHOW_ITEM_SKU',
  RECEIPT_SHOW_LEVY:             'RECEIPT_SHOW_LEVY',
  RECEIPT_SHOW_DISCOUNT:         'RECEIPT_SHOW_DISCOUNT',
  RECEIPT_SHOW_CHANGE:           'RECEIPT_SHOW_CHANGE',
  LOW_STOCK_DEFAULT_THRESHOLD:   'LOW_STOCK_DEFAULT_THRESHOLD',
  LOW_STOCK_ALERT_ENABLED:       'LOW_STOCK_ALERT_ENABLED',
  LOW_STOCK_ALERT_RECIPIENTS:    'LOW_STOCK_ALERT_RECIPIENTS',
  SALE_NUMBER_PREFIX:            'SALE_NUMBER_PREFIX',
  ORDER_NUMBER_PREFIX:           'ORDER_NUMBER_PREFIX',
  PAYSTACK_CURRENCY:             'PAYSTACK_CURRENCY',
  SALES_GLOBAL_DISCOUNT_RATE:    'SALES_GLOBAL_DISCOUNT_RATE',
  MAX_DISCOUNT_PERCENT:          'MAX_DISCOUNT_PERCENT',
  REFUND_VALIDITY_DAYS:          'REFUND_VALIDITY_DAYS',
  SPLIT_TENDER_ENABLED:          'SPLIT_TENDER_ENABLED',
  INVENTORY_LEVY_ENABLED:        'INVENTORY_LEVY_ENABLED',
  INVENTORY_LEVY_TYPE:           'INVENTORY_LEVY_TYPE',
  INVENTORY_LEVY_AMOUNT:         'INVENTORY_LEVY_AMOUNT',
  MOMO_PENDING_TIMEOUT_MINUTES:  'MOMO_PENDING_TIMEOUT_MINUTES',
  REQUIRE_CUSTOMER_PHONE_FOR_MOMO: 'REQUIRE_CUSTOMER_PHONE_FOR_MOMO',
  ALLOW_PRICE_OVERRIDE:          'ALLOW_PRICE_OVERRIDE',
  CASH_ROUNDING_ENABLED:         'CASH_ROUNDING_ENABLED',
  MOMO_PROMPT_CUSTOMER_TEXT:     'MOMO_PROMPT_CUSTOMER_TEXT',
  MOMO_AUTO_VERIFY_ON_WEBHOOK:   'MOMO_AUTO_VERIFY_ON_WEBHOOK',
  VAT_ENABLED:                   'VAT_ENABLED',
  NHIL_ENABLED:                  'NHIL_ENABLED',
  GETFUND_ENABLED:               'GETFUND_ENABLED',
  COVID_LEVY_ENABLED:            'COVID_LEVY_ENABLED',
  TAX_INCLUSIVE_PRICING:         'TAX_INCLUSIVE_PRICING',
  RECEIPT_SHOW_TAX_BREAKDOWN:    'RECEIPT_SHOW_TAX_BREAKDOWN',
  EOD_REPORT_ENABLED:            'EOD_REPORT_ENABLED',
  EOD_REPORT_TIME:               'EOD_REPORT_TIME',
  EOD_REPORT_RECIPIENTS:         'EOD_REPORT_RECIPIENTS',
  VOID_ALERT_ENABLED:            'VOID_ALERT_ENABLED',
  VOID_ALERT_RECIPIENTS:         'VOID_ALERT_RECIPIENTS',
  // ── Stage 3: inventory intelligence ──────────────────────────────────────
  NEGATIVE_STOCK_ALERT_ENABLED:  'NEGATIVE_STOCK_ALERT_ENABLED',
  AUTO_DEACTIVATE_ZERO_STOCK:    'AUTO_DEACTIVATE_ZERO_STOCK',
  LARGE_SALE_ALERT_ENABLED:      'LARGE_SALE_ALERT_ENABLED',
  LARGE_SALE_ALERT_THRESHOLD:    'LARGE_SALE_ALERT_THRESHOLD',
  SLOW_MOVING_DAYS_THRESHOLD:    'SLOW_MOVING_DAYS_THRESHOLD',
  OVERSTOCK_MULTIPLIER:          'OVERSTOCK_MULTIPLIER',
  STOCK_COUNT_REMINDER_DAYS:     'STOCK_COUNT_REMINDER_DAYS',
  // ── Stage 3: reports expansion ────────────────────────────────────────────
  WEEKLY_REPORT_ENABLED:         'WEEKLY_REPORT_ENABLED',
  WEEKLY_REPORT_DAY:             'WEEKLY_REPORT_DAY',
  MONTHLY_REPORT_ENABLED:        'MONTHLY_REPORT_ENABLED',
  DAILY_OPENING_EMAIL_ENABLED:   'DAILY_OPENING_EMAIL_ENABLED',
  DAILY_OPENING_EMAIL_TIME:      'DAILY_OPENING_EMAIL_TIME',
  REPORT_INCLUDE_COGS:           'REPORT_INCLUDE_COGS',
  REPORT_INCLUDE_LEVY:           'REPORT_INCLUDE_LEVY',
  FISCAL_YEAR_START_MONTH:       'FISCAL_YEAR_START_MONTH',
  // ── Stage 3: security & operations ───────────────────────────────────────
  SESSION_TIMEOUT_MINUTES:       'SESSION_TIMEOUT_MINUTES',
  MAX_LOGIN_ATTEMPTS:            'MAX_LOGIN_ATTEMPTS',
  LOCKOUT_DURATION_MINUTES:      'LOCKOUT_DURATION_MINUTES',
  POS_IDLE_LOCK_MINUTES:         'POS_IDLE_LOCK_MINUTES',
  REQUIRE_PASSWORD_CHANGE_DAYS:  'REQUIRE_PASSWORD_CHANGE_DAYS',
} as const;

export type SettingName = typeof SETTINGS[keyof typeof SETTINGS];

export type SettingType = 'string' | 'textarea' | 'boolean' | 'number' | 'time' | 'enum';

export interface SettingDefinition {
  name:             SettingName;
  label:            string;
  value:            string;
  group:            'general' | 'inventory' | 'payments' | 'ecommerce' | 'reports';
  editable:         boolean;
  type:             SettingType;
  unit?:            string;
  hint?:            string;
  options?:         string[];
  min?:             number;
  max?:             number;
  restart_required?: boolean;
}

export const SETTING_DEFINITIONS: SettingDefinition[] = [
  // ── Business identity ─────────────────────────────────────────────────────
  {
    name:     SETTINGS.BUSINESS_NAME,
    label:    'Business display name',
    value:    'Elegance by Sconia',
    group:    'general',
    editable: true,
    type:     'string',
    hint:     'Appears on receipts, emails, and report headers.',
  },
  {
    name:     SETTINGS.BUSINESS_TAGLINE,
    label:    'Business tagline',
    value:    '',
    group:    'general',
    editable: true,
    type:     'string',
    hint:     'Short line shown under the name on receipts and in report emails.',
  },
  {
    name:     SETTINGS.BUSINESS_PHONE,
    label:    'Business contact phone',
    value:    '+233507738490',
    group:    'general',
    editable: true,
    type:     'string',
    hint:     'Printed on receipts when "Show phone" is enabled.',
  },
  {
    name:     SETTINGS.BUSINESS_EMAIL,
    label:    'Business contact email',
    value:    'elegancebysconia@gmail.com',
    group:    'general',
    editable: true,
    type:     'string',
    hint:     'Printed on receipts when "Show email" is enabled.',
  },
  {
    name:     SETTINGS.BUSINESS_WEBSITE,
    label:    'Business website',
    value:    '',
    group:    'general',
    editable: true,
    type:     'string',
    hint:     'Printed on receipts when "Show website" is enabled. Leave blank to hide.',
  },
  {
    name:     SETTINGS.BUSINESS_REGISTRATION_NUMBER,
    label:    'Business registration number',
    value:    '',
    group:    'general',
    editable: true,
    type:     'string',
    hint:     'Certificate of Incorporation number. Printed in the receipt header when set.',
  },
  {
    name:     SETTINGS.GRA_TIN,
    label:    'GRA Tax Identification Number (TIN)',
    value:    '',
    group:    'general',
    editable: true,
    type:     'string',
    hint:     'Required for VAT receipts. Printed below the business name when set.',
  },

  // ── Store address ─────────────────────────────────────────────────────────
  {
    name:     SETTINGS.RECEIPT_STORE_ADDRESS,
    label:    'Store / business address',
    value:    '',
    group:    'general',
    editable: true,
    type:     'textarea',
    hint:     'Printed under the business name. Leave blank to hide.',
  },

  // ── Receipt layout ────────────────────────────────────────────────────────
  {
    name:     SETTINGS.RECEIPT_PAPER_WIDTH,
    label:    'Receipt paper width',
    value:    '80mm',
    group:    'general',
    editable: true,
    type:     'enum',
    options:  ['58mm', '80mm'],
    hint:     'Match your thermal printer roll width.',
  },
  {
    name:     SETTINGS.RECEIPT_SHOW_LOGO,
    label:    'Show logo mark on receipts',
    value:    'true',
    group:    'general',
    editable: true,
    type:     'boolean',
  },
  {
    name:     SETTINGS.RECEIPT_SHOW_PHONE,
    label:    'Show phone number on receipts',
    value:    'true',
    group:    'general',
    editable: true,
    type:     'boolean',
  },
  {
    name:     SETTINGS.RECEIPT_SHOW_EMAIL,
    label:    'Show email address on receipts',
    value:    'false',
    group:    'general',
    editable: true,
    type:     'boolean',
  },
  {
    name:     SETTINGS.RECEIPT_SHOW_WEBSITE,
    label:    'Show website on receipts',
    value:    'false',
    group:    'general',
    editable: true,
    type:     'boolean',
  },
  {
    name:     SETTINGS.RECEIPT_SHOW_CASHIER,
    label:    'Show cashier name on receipts',
    value:    'true',
    group:    'general',
    editable: true,
    type:     'boolean',
  },
  {
    name:     SETTINGS.RECEIPT_SHOW_SALE_REF,
    label:    'Show sale reference number on receipts',
    value:    'true',
    group:    'general',
    editable: true,
    type:     'boolean',
  },
  {
    name:     SETTINGS.RECEIPT_SHOW_UNIT_PRICES,
    label:    'Show unit price breakdown per item',
    value:    'true',
    group:    'general',
    editable: true,
    type:     'boolean',
    hint:     'Prints "qty × price" below each item line.',
  },
  {
    name:     SETTINGS.RECEIPT_SHOW_ITEM_SKU,
    label:    'Show item SKU on receipts',
    value:    'false',
    group:    'general',
    editable: true,
    type:     'boolean',
  },
  {
    name:     SETTINGS.RECEIPT_SHOW_DISCOUNT,
    label:    'Show discount line on receipts',
    value:    'true',
    group:    'general',
    editable: true,
    type:     'boolean',
    hint:     'Only appears when a discount was applied to the sale.',
  },
  {
    name:     SETTINGS.RECEIPT_SHOW_LEVY,
    label:    'Show levy line on receipts',
    value:    'true',
    group:    'general',
    editable: true,
    type:     'boolean',
    hint:     'Only appears when the inventory levy is enabled and greater than zero.',
  },
  {
    name:     SETTINGS.RECEIPT_SHOW_CHANGE,
    label:    'Show change given on receipts',
    value:    'true',
    group:    'general',
    editable: true,
    type:     'boolean',
    hint:     'Only appears on cash sales.',
  },
  {
    name:     SETTINGS.RECEIPT_SHOW_REFUND_POLICY,
    label:    'Show refund policy on receipts',
    value:    'true',
    group:    'general',
    editable: true,
    type:     'boolean',
  },
  {
    name:     SETTINGS.RECEIPT_FOOTER_MESSAGE,
    label:    'Receipt footer message',
    value:    'Thank you for shopping with us!',
    group:    'general',
    editable: true,
    type:     'string',
  },
  {
    name:     SETTINGS.RECEIPT_FOOTER_LINE_2,
    label:    'Receipt footer — second line',
    value:    '',
    group:    'general',
    editable: true,
    type:     'string',
    hint:     'Optional second line (social handles, promo text). Leave blank to hide.',
  },

  // ── Inventory ─────────────────────────────────────────────────────────────
  {
    name:     SETTINGS.LOW_STOCK_DEFAULT_THRESHOLD,
    label:    'Default low-stock warning level',
    value:    '5',
    group:    'inventory',
    editable: true,
    type:     'number',
    unit:     'units',
    hint:     'Pre-filled when creating a new variant.',
    min:      1,
    max:      10000,
  },
  {
    name:     SETTINGS.LOW_STOCK_ALERT_ENABLED,
    label:    'Send low-stock email alerts',
    value:    'true',
    group:    'inventory',
    editable: true,
    type:     'boolean',
  },
  {
    name:     SETTINGS.LOW_STOCK_ALERT_RECIPIENTS,
    label:    'Additional low-stock alert recipients',
    value:    '',
    group:    'inventory',
    editable: true,
    type:     'string',
    hint:     'Comma-separated email addresses. Owner always receives alerts.',
  },
  {
    name:     SETTINGS.SALE_NUMBER_PREFIX,
    label:    'Sale number prefix',
    value:    'SL',
    group:    'inventory',
    editable: false,
    type:     'string',
    hint:     'Cannot be changed after sales have been recorded.',
  },
  {
    name:     SETTINGS.ORDER_NUMBER_PREFIX,
    label:    'Online order number prefix',
    value:    'O',
    group:    'ecommerce',
    editable: false,
    type:     'string',
  },

  // ── Payments ──────────────────────────────────────────────────────────────
  {
    name:     SETTINGS.PAYSTACK_CURRENCY,
    label:    'Paystack currency code',
    value:    'GHS',
    group:    'payments',
    editable: false,
    type:     'string',
    hint:     'Fixed to GHS. Contact support to change.',
  },
  {
    name:     SETTINGS.SALES_GLOBAL_DISCOUNT_RATE,
    label:    'Global sale discount rate',
    value:    '0',
    group:    'payments',
    editable: true,
    type:     'number',
    unit:     '%',
    hint:     'Automatically applied to every sale. Set to 0 to disable.',
    min:      0,
    max:      100,
  },
  {
    name:     SETTINGS.MAX_DISCOUNT_PERCENT,
    label:    'Maximum total discount allowed',
    value:    '100',
    group:    'payments',
    editable: true,
    type:     'number',
    unit:     '%',
    hint:     'Caps the combined global + manual discount as a % of the sale subtotal.',
    min:      0,
    max:      100,
  },
  {
    name:     SETTINGS.REFUND_VALIDITY_DAYS,
    label:    'Return acceptance period',
    value:    '7',
    group:    'payments',
    editable: true,
    type:     'number',
    unit:     'days',
    min:      0,
    max:      365,
  },
  {
    name:     SETTINGS.SPLIT_TENDER_ENABLED,
    label:    'Allow split payment (cash + mobile money)',
    value:    'false',
    group:    'payments',
    editable: true,
    type:     'boolean',
  },
  {
    name:     SETTINGS.INVENTORY_LEVY_ENABLED,
    label:    'Apply internal levy per unit sold',
    value:    'false',
    group:    'payments',
    editable: true,
    type:     'boolean',
  },
  {
    name:      SETTINGS.INVENTORY_LEVY_TYPE,
    label:     'Levy calculation method',
    value:     'flat',
    group:     'payments',
    editable:  true,
    type:      'enum',
    options:   ['flat', 'percent'],
    hint:      '"flat" = fixed GHS per unit sold. "percent" = % of the sale price.',
  },
  {
    name:     SETTINGS.INVENTORY_LEVY_AMOUNT,
    label:    'Levy amount',
    value:    '0',
    group:    'payments',
    editable: true,
    type:     'number',
    hint:     'GHS per unit (flat mode) or percentage of unit price (percent mode).',
    min:      0,
    max:      100000,
  },
  {
    name:     SETTINGS.MOMO_PENDING_TIMEOUT_MINUTES,
    label:    'Mobile money payment timeout',
    value:    '15',
    group:    'payments',
    editable: true,
    type:     'number',
    unit:     'minutes',
    hint:     'Unconfirmed Momo payments are cancelled after this period.',
    min:      1,
    max:      1440,
  },
  {
    name:     SETTINGS.REQUIRE_CUSTOMER_PHONE_FOR_MOMO,
    label:    'Require customer phone for Momo payments',
    value:    'true',
    group:    'payments',
    editable: true,
    type:     'boolean',
    hint:     'When disabled, cashiers can submit Momo payments without a phone number.',
  },
  {
    name:     SETTINGS.ALLOW_PRICE_OVERRIDE,
    label:    'Allow selling price override at POS',
    value:    'true',
    group:    'payments',
    editable: true,
    type:     'boolean',
    hint:     'When disabled, no one can override unit prices at checkout — even users with the override permission.',
  },
  {
    name:     SETTINGS.CASH_ROUNDING_ENABLED,
    label:    'Round cash change to nearest 50 pesewas',
    value:    'false',
    group:    'payments',
    editable: true,
    type:     'boolean',
    hint:     'Rounds change due to the nearest GHS 0.50 to avoid small-coin shortages.',
  },
  {
    name:     SETTINGS.MOMO_PROMPT_CUSTOMER_TEXT,
    label:    'Momo payment instructions shown to cashier',
    value:    '',
    group:    'payments',
    editable: true,
    type:     'string',
    hint:     'Shown on the payment pending screen. Leave blank to use the default message.',
  },
  {
    name:     SETTINGS.MOMO_AUTO_VERIFY_ON_WEBHOOK,
    label:    'Auto-confirm Momo payments via Paystack webhook',
    value:    'true',
    group:    'payments',
    editable: true,
    type:     'boolean',
    hint:     'When enabled, a successful Paystack webhook instantly marks the sale as paid. Disable to require manual verification.',
  },

  // ── Ghana tax (GRA compliance) ─────────────────────────────────────────────
  {
    name:     SETTINGS.VAT_ENABLED,
    label:    'Apply VAT (15%)',
    value:    'false',
    group:    'payments',
    editable: true,
    type:     'boolean',
    hint:     'GRA standard-rate VAT. Enable only if the business is VAT-registered.',
  },
  {
    name:     SETTINGS.NHIL_ENABLED,
    label:    'Apply NHIL (2.5%)',
    value:    'false',
    group:    'payments',
    editable: true,
    type:     'boolean',
    hint:     'National Health Insurance Levy. Applied alongside VAT for standard-rate businesses.',
  },
  {
    name:     SETTINGS.GETFUND_ENABLED,
    label:    'Apply GETFund levy (2.5%)',
    value:    'false',
    group:    'payments',
    editable: true,
    type:     'boolean',
    hint:     'Ghana Education Trust Fund levy. Applied alongside VAT for standard-rate businesses.',
  },
  {
    name:     SETTINGS.COVID_LEVY_ENABLED,
    label:    'Apply COVID-19 recovery levy (1%)',
    value:    'false',
    group:    'payments',
    editable: true,
    type:     'boolean',
    hint:     'COVID-19 Health Recovery Levy. Applied alongside VAT for standard-rate businesses.',
  },
  {
    name:     SETTINGS.TAX_INCLUSIVE_PRICING,
    label:    'Prices in system are tax-inclusive',
    value:    'true',
    group:    'payments',
    editable: true,
    type:     'boolean',
    hint:     'When enabled, taxes are reverse-calculated from the selling price for display only. When disabled, taxes are added on top of the listed price.',
  },
  {
    name:     SETTINGS.RECEIPT_SHOW_TAX_BREAKDOWN,
    label:    'Show tax breakdown on receipts',
    value:    'false',
    group:    'general',
    editable: true,
    type:     'boolean',
    hint:     'Prints individual VAT / NHIL / GETFund / COVID levy lines on the receipt. Only applies when any tax is enabled.',
  },

  // ── Reports & Alerts ──────────────────────────────────────────────────────
  {
    name:     SETTINGS.EOD_REPORT_ENABLED,
    label:    'Send daily sales summary email',
    value:    'true',
    group:    'reports',
    editable: true,
    type:     'boolean',
  },
  {
    name:             SETTINGS.EOD_REPORT_TIME,
    label:            'Daily report send time',
    value:            '22:00',
    group:            'reports',
    editable:         true,
    type:             'time',
    hint:             '24-hour format (HH:mm). Server must restart for a time change to take effect.',
    restart_required: true,
  },
  {
    name:     SETTINGS.EOD_REPORT_RECIPIENTS,
    label:    'Additional report recipients',
    value:    '',
    group:    'reports',
    editable: true,
    type:     'string',
    hint:     'Comma-separated emails. Owner always receives reports.',
  },
  {
    name:     SETTINGS.VOID_ALERT_ENABLED,
    label:    'Email owner when a sale is voided',
    value:    'true',
    group:    'reports',
    editable: true,
    type:     'boolean',
    hint:     'Sends an immediate alert any time a cashier voids a completed sale.',
  },
  {
    name:     SETTINGS.VOID_ALERT_RECIPIENTS,
    label:    'Additional void alert recipients',
    value:    '',
    group:    'reports',
    editable: true,
    type:     'string',
    hint:     'Comma-separated emails. Owner always receives void alerts.',
  },

  // ── Inventory intelligence ────────────────────────────────────────────────
  {
    name:     SETTINGS.NEGATIVE_STOCK_ALERT_ENABLED,
    label:    'Alert owner when stock hits zero (real-time)',
    value:    'true',
    group:    'inventory',
    editable: true,
    type:     'boolean',
    hint:     'Sends an immediate email the moment a sale drains the last unit of any variant.',
  },
  {
    name:     SETTINGS.AUTO_DEACTIVATE_ZERO_STOCK,
    label:    'Auto-deactivate variants when stock reaches zero',
    value:    'false',
    group:    'inventory',
    editable: true,
    type:     'boolean',
    hint:     'When enabled, variants are automatically set to inactive when their stock hits 0 in a sale.',
  },
  {
    name:     SETTINGS.LARGE_SALE_ALERT_ENABLED,
    label:    'Alert owner on unusually large sales',
    value:    'false',
    group:    'reports',
    editable: true,
    type:     'boolean',
    hint:     'Fires an immediate email when a single sale amount meets or exceeds the threshold below.',
  },
  {
    name:     SETTINGS.LARGE_SALE_ALERT_THRESHOLD,
    label:    'Large sale alert threshold',
    value:    '1000',
    group:    'reports',
    editable: true,
    type:     'number',
    unit:     'GHS',
    hint:     'Minimum sale amount (GHS) that triggers the large sale alert.',
    min:      0,
    max:      1000000,
  },
  {
    name:     SETTINGS.SLOW_MOVING_DAYS_THRESHOLD,
    label:    'Slow-moving item threshold',
    value:    '30',
    group:    'reports',
    editable: true,
    type:     'number',
    unit:     'days',
    hint:     'Variants with no sales in the last N days are flagged as slow-moving in EOD and weekly reports.',
    min:      7,
    max:      365,
  },
  {
    name:     SETTINGS.OVERSTOCK_MULTIPLIER,
    label:    'Overstock flag multiplier',
    value:    '5',
    group:    'reports',
    editable: true,
    type:     'number',
    hint:     'Variants with stock > N × low-stock threshold are flagged as overstock in reports.',
    min:      2,
    max:      100,
  },
  {
    name:     SETTINGS.STOCK_COUNT_REMINDER_DAYS,
    label:    'Physical stock count reminder interval',
    value:    '30',
    group:    'inventory',
    editable: true,
    type:     'number',
    unit:     'days',
    hint:     'Owner receives a reminder email to do a physical stock count on this schedule. Set to 0 to disable.',
    min:      0,
    max:      365,
  },

  // ── Reports expansion ─────────────────────────────────────────────────────
  {
    name:     SETTINGS.WEEKLY_REPORT_ENABLED,
    label:    'Send weekly sales summary email',
    value:    'true',
    group:    'reports',
    editable: true,
    type:     'boolean',
  },
  {
    name:     SETTINGS.WEEKLY_REPORT_DAY,
    label:    'Weekly report send day',
    value:    'Sunday',
    group:    'reports',
    editable: true,
    type:     'enum',
    options:  ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    hint:     'Day of the week the weekly digest email is sent (at the same time as the daily report).',
    restart_required: true,
  },
  {
    name:     SETTINGS.MONTHLY_REPORT_ENABLED,
    label:    'Send monthly P&L summary email',
    value:    'false',
    group:    'reports',
    editable: true,
    type:     'boolean',
    hint:     'Sends a monthly profit & loss summary on the first day of each month.',
  },
  {
    name:     SETTINGS.DAILY_OPENING_EMAIL_ENABLED,
    label:    'Send morning briefing email',
    value:    'false',
    group:    'reports',
    editable: true,
    type:     'boolean',
    hint:     'Sends a morning summary (yesterday close, low stock, overstock flags) to the owner.',
  },
  {
    name:             SETTINGS.DAILY_OPENING_EMAIL_TIME,
    label:            'Morning briefing send time',
    value:            '08:00',
    group:            'reports',
    editable:         true,
    type:             'time',
    hint:             '24-hour format. Server restart required to apply time change.',
    restart_required: true,
  },
  {
    name:     SETTINGS.REPORT_INCLUDE_COGS,
    label:    'Include cost of goods & gross profit in reports',
    value:    'true',
    group:    'reports',
    editable: true,
    type:     'boolean',
    hint:     'Shows the COGS and gross profit section in EOD and weekly summary emails.',
  },
  {
    name:     SETTINGS.REPORT_INCLUDE_LEVY,
    label:    'Include levy accrual in reports',
    value:    'true',
    group:    'reports',
    editable: true,
    type:     'boolean',
    hint:     'Shows the levy total in EOD and weekly summary emails.',
  },
  {
    name:     SETTINGS.FISCAL_YEAR_START_MONTH,
    label:    'Fiscal year start month',
    value:    '1',
    group:    'reports',
    editable: true,
    type:     'number',
    hint:     'Month number (1 = January). Affects YTD revenue labels in report emails.',
    min:      1,
    max:      12,
  },

  // ── Security & operations ─────────────────────────────────────────────────
  {
    name:             SETTINGS.SESSION_TIMEOUT_MINUTES,
    label:            'Session idle timeout',
    value:            '480',
    group:            'general',
    editable:         true,
    type:             'number',
    unit:             'minutes',
    hint:             'Server destroys idle sessions after this period. 480 = 8 hours. Restart required to apply.',
    min:              5,
    max:              10080,
    restart_required: true,
  },
  {
    name:     SETTINGS.MAX_LOGIN_ATTEMPTS,
    label:    'Maximum failed login attempts before lockout',
    value:    '5',
    group:    'general',
    editable: true,
    type:     'number',
    hint:     'Accounts are locked after this many consecutive failed login attempts. Set to 0 to disable.',
    min:      0,
    max:      20,
  },
  {
    name:     SETTINGS.LOCKOUT_DURATION_MINUTES,
    label:    'Account lockout duration',
    value:    '30',
    group:    'general',
    editable: true,
    type:     'number',
    unit:     'minutes',
    hint:     'How long a locked account stays locked before automatically unlocking.',
    min:      1,
    max:      1440,
  },
  {
    name:     SETTINGS.POS_IDLE_LOCK_MINUTES,
    label:    'POS idle lock timeout',
    value:    '0',
    group:    'payments',
    editable: true,
    type:     'number',
    unit:     'minutes',
    hint:     'Lock the POS screen after this many minutes of inactivity. Set to 0 to disable.',
    min:      0,
    max:      60,
  },
  {
    name:     SETTINGS.REQUIRE_PASSWORD_CHANGE_DAYS,
    label:    'Force password change after N days',
    value:    '0',
    group:    'general',
    editable: true,
    type:     'number',
    unit:     'days',
    hint:     'Redirects staff to the password change page after this many days. Set to 0 to never enforce.',
    min:      0,
    max:      365,
  },
];
